services:
  app:
    image: app
    build:
      context: ./
      target: dev
    working_dir: /usr/src/app/
    environment:
      DATABASE_URL: postgres://app_dev:dev_password@database:5432/dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules/
    command: bun run dev

  database:
    image: postgres:16.4
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: app_dev
      POSTGRES_PASSWORD: dev_password
      ALLOW_IP_RANGE: "172.0.0.0/8"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app_dev", "-d", "dev"]
      interval: 3s
      timeout: 3s
      retries: 5
    command: ["postgres", "-c", "log_statement=none"]
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
